on: [push]
name: Build and push

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          id: build-push-acr
          uses:  azure/acr-build@v1
          with:
            service_principal: ${{ secrets.SERVICE_PRINCIPAL }}
            service_principal_password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
            tenant: ${{ secrets.TENANT }}
            registry: ${{ secrets.REGISTRY }}
            repository: ${{ secrets.REPOSITORY }}
            image: azure-vote-front
            folder: azure-vote
            branch: main
            tag: v1
            git_access_token: ${{ secrets.GITHUB_TOKEN }}