on: [push]
name: Build and push

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -f azure-vote/Dockerfile azure-vote -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/unycriss:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/unycriss:latest

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            # dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            dns-name-label: unycriss
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/unycriss:latest
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: latest
            location: 'brazilsouth'

        # - name: Build and Push to ACR
        #   uses: docker/build-push-action@v2
        #   with:
        #     push: true
        #     tags: latest
        #     file: azure-vote/Dockerfile